events {}
http {
    server {
        listen 80;
 
        location /trip {
            proxy_pass http://internal-travelmemory-backend-ilb-923127743.ap-south-1.elb.amazonaws.com;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
 
        location /hello {
            proxy_pass http://internal-travelmemory-backend-ilb-923127743.ap-south-1.elb.amazonaws.com;
        }
 
        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }
    }
}
